<h1>Python libraries for data analysis</h1>


<li><b><span style="color:blue">Numpy</span></b>: supports numerical and array operations
<li><b><span style="color:blue">Scipy</span></b>: open source library for mathematics and scientific computing
<li><b><span style="color:blue">Pandas</span></b>: supports data manipulation and analysis
<li><b><span style="color:blue">Visualization libraries</span></b>: matplotlib, seaborne, bokeh, plotly, gmplot, and many others provide support for charts and graphs

<h1>numpy</h1>


<h2>Why numpy?</h2>
<li>Multi-dimensional arrays:
<li>Faster and more space efficient than lists 
<li>Can incorporate C/C++/Fortran code
<li>Linear algebra, Fourier transforms, Random number support



<h2>numpy array</h2>

In [2]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(type(ax))


<class 'numpy.ndarray'>


<li>A numpy array has a data type associated with its elements
<li>and elements need to be of the same data type
<li>But an element could be an 'arbitrarily' complex object

In [3]:
#all elements must be of the same type, shouldnt be a problem for me!

np.array([1,2,'a'])

array(['1', '2', 'a'], dtype='<U21')

In [4]:
#type: object is considered a type
np.array([{'a':1,'b':2},4])

array([{'a': 1, 'b': 2}, 4], dtype=object)

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

<h4>The <i>dtype</i> attribute</h4>
<li>Stores the data type in the array
<li>numpy makes a best guess of the data type

In [5]:
ax = np.array([[1,2,3],[5,6,7,8.3]])
ax.dtype
ax
#won't make an array if they arent the same size
#np.array initializes an array using the numpy library
#if i call dtyp on the array initialized 

array([list([1, 2, 3]), list([5, 6, 7, 8.3])], dtype=object)

In [6]:
ax = np.array([{'a':1,'b':2},4])
ax.dtype 
#O stands for object here

dtype('O')

In [7]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')
#np.arrary and then the variable means that it is of that type
#cool


[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<li>The <i>astype</i> function converts from one type to another


In [8]:
ax = np.array([1,2,3,'4'])
print(ax)
print(ax.dtype)
ax.astype(int)
#so instead of initializing a new array, it takes the array that currently exists and casts it

['1' '2' '3' '4']
<U21


array([1, 2, 3, 4])

In [9]:
ay = ax.astype(float)
print(ay)
ay.dtype
#do not call np again when casting, an initialized np will retain the properties that are associated

[1. 2. 3. 4.]


dtype('float64')

<h2>Basic operations</h2>

<h4>statistical operations</h4>

In [10]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')
#sep=\n will separate the outputs, its like punctuation at the end applied to the rest
#call the statistical operations on the array as a whole


97.50000000000001
19.500000000000004
3.8429155598321434


<h4>arrray arithmetic operations</h4>
<li><b>Important</b>: Arrays must be the same size!

In [11]:
x = np.array([13,24,21.2,17.6,21.7],'float')
y = np.array([1,3,4,7,2],'float')
x - y

array([12. , 21. , 17.2, 10.6, 19.7])

In [12]:
x+y

array([14. , 27. , 25.2, 24.6, 23.7])

In [13]:
x*y #multi will do each element but not sum them, multi not dot product

array([ 13. ,  72. ,  84.8, 123.2,  43.4])

In [14]:
x/y

array([13.        ,  8.        ,  5.3       ,  2.51428571, 10.85      ])

<h2>Multi-dimensional arrays</h2>

In [15]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)
#this is a 2d array

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [16]:
ax[1,3] #indexing
#calling the name of the array and then the number will pull the valued stored at that location
#that is called indexing


13.0

<h3>Slicing</h3>

In [17]:
xl=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
xl[1][3]
#same 
#this is not an array yet
a = np.array(xl,int)
a[1][3]
#array will take both kinds of calls, the lsit operator will not because it is 1 dimensional

13

In [18]:
ax[1:3,2:4]
#this is like drawing a square on my matrice
#Intersection between ax[1:3,:] and ax[:,2:4]

array([[12., 13.],
       [22., 23.]])

In [19]:
ax[:,2:]

array([[ 2.,  3.,  4.,  5.],
       [12., 13., 14., 15.],
       [22., 23., 24., 25.]])

<h3>Reshaping</h3>
<li>nd arrays can be reshaped as long as the total dimensionality is unchanged


In [20]:
print(ax.shape)
ax.reshape(9,2)
ax.reshape(10,3)
#total dimensionality is like using the factors in different ways
#i wonder if I can project a 2d array into a 3d array using another dimension and reshaping?

(3, 6)


ValueError: cannot reshape array of size 18 into shape (10,3)

<h3>Creating nd arrays</h3>

<h4>Using the <i>array</i> function</h4>

In [21]:
data = [[0,1,2,3,4],[5,6,7,8,9]]
data_array = np.array(data)
data_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h4>Using initializers</h4>

<li>The <i>arrange</i> (array range) function


In [22]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)
ax.dtype
#arange starts at 0 and increments by 1 unless told otherwise

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


dtype('int64')

In [23]:
ax = np.arange(10)**2
print(ax)
#that takes the square of the number


[ 0  1  4  9 16 25 36 49 64 81]


<li>The <i>ones</i> function creates an array of 1s (floats)

In [24]:
ax = np.ones(10)
print(ax)
ax.dtype
#.ones put your 1s up

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [25]:
ax = np.array([[1,2,3,4],[5,6,7,8]])
ay = np.ones_like(ax)
ay
#ones_like makes the same dimensions but just of the value one
#this is useful for an identity matrix


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:

ay = np.zeros_like(ax)
ay

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

<li>The <i>identity(n)</i> function creates an identity matrix of order n

In [27]:
np.identity(10)
#NOW THAT IS A USEFUL FUCKING FUNCTION

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<li>The function <i>empty</i> creates an "empty" array
<li>Values in the array are "garbage" values

In [28]:
np.empty([2,3],float)

array([[0., 0., 0.],
       [0., 0., 0.]])

<h3>Matrix multiplication</h3>


In [29]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [30]:
np.dot(ay,ay.reshape(10,2)) #Dot product
#I dont really know what happened here but thats ok

array([[220, 265],
       [220, 265]])

<h2>Lists vs numpy arrays</h2>
<li>Lists are heterogenous. Elements of a list can be of multiple types
<li>Numpy arrays are homogeneous. Elements can be of only one type
<li>Both are mutable
<li>Homogeneity makes indexed access faster and more memory efficient
<li>numpy are optimized for matrix operations
<li>numpy provides random number support


<h3>numpy arrays are homogeneous</h3>

<h3>numpy arrays are faster</h3>

In [31]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]])

<h4>Functionalize this</h4>


In [32]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0, 0, 15)

<h4>Do the same with python lists</h4>


In [33]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10)

datetime.timedelta(0, 0, 17)

<b>Digression</b> the zip function
<li>Takes two "iterables" as arguments
<li>And pairs the elements in the iterables

In [34]:
a = [1,2,3]
b =['a','b','c']
list(zip(a,b))

[(1, 'a'), (2, 'b'), (3, 'c')]

<b>Digression:</b> List comprehension
<li>A mechanism for creating new lists from existing lists
<li>"Describe" the new list to generate it!
<li>Does away with for loops etc. and is a lot faster

In [35]:
a = [1,2,3]
b = ['a','b','c']
[(a[i],b[i]) for i in range(len(a))]

[(1, 'a'), (2, 'b'), (3, 'c')]

In [36]:
a = [1,2,3,4,5,6,7,8]
["Even" if val%2 == 0 else "Odd" for val in a]

['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even']

<h4>Compare the two</h4>

In [37]:
for n in [10,100,1000,10000,1000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00.000014	0:00:00.000016
100	0:00:00.000011	0:00:00.000067
1000	0:00:00.000009	0:00:00.001227
10000	0:00:00.000266	0:00:00.007225
1000000	0:00:00.003598	0:00:01.569025


<h3>numpy indexing vs list indexing</h3>
<li>numpy arrays use direct indexing
<li>lists use chained indexing

In [38]:
ax = np.array([1,2,3,4,8,9])
x = [1,2,3,4,8,9]

#Extract the first and last elements from the numpy array into a single array
ax[[0,-1]]

#Extract the first and last elements from the list into a new list
[x[0],x[-1]]

[1, 9]

<h3>numpy slicing vs list slicing</h3>

In [39]:
ax = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
ax[1:3,1:3]
#like drawing a square there


array([[22, 23],
       [32, 33]])

In [40]:
ax

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [42]:
lx = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]

<h2>batch operations on nd arrays</h2>
<li>numpy arrays allow the application of batch operations on all elements of an array
<li>without having to write a for loop or use an iterator
<li>by <i>vectorizing</i> operations, numpy is much faster than the slow for loop structure of python


<h3>batch: selecting elements using a boolean mask</h3>
<li> A boolean max applies a condition to each element in turn
<li> And returns an array of boolean with
<ul>
<li> True for each value that satisfies the condition
<li> False for every other value

In [43]:
ax = np.array([1,4,7,9,2,3,10,11,34,2])
ax < 7
#less than is automatically vectorized
#vectorize means applies to all of them at once

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

<h4>The mask can be applied as a selection operator on the array

In [45]:
ax[ax<7]
#print the array such that it prints the elements from that array that follow the following condition


array([1, 4, 2, 3, 2])

<h4>The mask doesn't have to be constructed on the same array</h4>
<li>But the mask and the array should have the same dimensions

In [47]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
#apply the condition of a separate name to pick which entries are chosen to add
names[bonus > 130000]


array(['Bill', 'Sally'], dtype='<U8')

<h3>batch: arithmetic operations</h3>
<li>+, -, *, /, scalar multiplication do an element by element operation

In [49]:
import numpy as np
ax = np.array([[1,2,3],[4,5,6]])
1/ax

#applies to each individually

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

<h3>batch: functional artithmetic operators</h3>

In [53]:
ax = np.array([4,9,2,4,0,25,0])
print(np.sum(ax>5))
#how many entries is this TRUE FOR
print(np.sum(ax[ax>5]))
#adds the entries FOR WHICH IT IS TRUE
print(np.count_nonzero(ax))
#how many entries are nonzero

print(np.any(ax>10))
#are there any such that this condition is true?
print(np.all(ax>0))
#is this condition true for all of them?

2
34
5
True
False


<h3>Logical operations with numpy</h3>
<li>logical_or
<li>logical_and

In [55]:
np.logical_and(bonus>90000.0, bonus<400000 )
#satisfies both of these conditions


array([ True, False, False,  True, False])

<h4>Boolean operators</h4>
<li>the numpy equivalent of "and" is "&"
<li>the numpy equivalent of "or" is "|"
<li>the numpy equivalent of "not" is "!"


In [57]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
print(np.sum(bonus[(bonus>50000) & (bonus < 200000)]))
print(np.sum(bonus[(names=="Bill") | (names == "Qing")]))
print(np.sum(bonus[(names!="Bill")]))
print(np.sum(bonus[~((names=="Bill") | (names == "Qing"))]))
#I dont understand the last line

150135.86
236191.8
632150.55
628259.31


In [59]:
bonus[(names=="Bill") | (names == "Qing")]
#picks the entry associated in bonus, like bill chooses the pointer and then applies that pointer to the new array

array([232300.56,   3891.24])

<b>Problem</b> Calculate the mean and median bonus amount for all female employees with bonus less than $100,000

In [61]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])

np.mean(bonus[gender=='F'])
#now this is a dope way to use this

193342.35

<b>Problem</b> Return an nd array containing the names of all female employees with bonus less than $100,000

In [64]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])

names[gender == 'F']
#names[bonus[(gender == 'F') & (bonus<100000)] ]
#I can't condition on two different sets in the same & statement
a1=gender=='F'
a2=bonus < 100000
names[a1 & a2]
names[(gender=='F') & (bonus<100000)]

array(['Qing', 'Savitri'], dtype='<U8')

<h3>batch: Selecting elements using where</h3>
<li><i>where</i> function creates a new array using a conditional expression
<li>Somewhat like the if function in an excel spreadsheet

<h2>axes</h2>
<li>The axis parameter tells numpy which axis to operate along

In [66]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ax = ax.reshape(3,4)
print(ax)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h4>sum each column</h4>

In [68]:
ax.sum(axis=0)
#axis is where it ends up, for every entry in row 0, perform this operation along the column

array([15, 18, 21, 24])

<h4>sum each row</h4>

In [69]:
ax.sum(axis=1)

array([10, 26, 42])

<h4>sum by depth</h4>

In [71]:
ax=ax.reshape(2,3,2)
ax.sum(axis=2)
#so 3 dimensional array here, that's a bit difficult to picture

array([[ 3,  7, 11],
       [15, 19, 23]])

<h4>add an axis to an array</h4>


In [72]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ax)
ax[:,np.newaxis]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

<h4>Easy to add n-dimensions to an nd array using newaxis</h4>

In [73]:
ax = ax.reshape(4,3)
ax[np.newaxis,np.newaxis,np.newaxis].shape

(1, 1, 1, 4, 3)

In [74]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

<h2>Broadcasting</h2>
<li>arithmetic operations work element by element
<li>so both arrays have to be of the same length
<li><b>broadcasting</b> is used for arithmetic on arrays of different shapes

In [75]:
ax = np.array([1,2,3])
ay = np.array([3,2,1])
ax+ay

array([4, 4, 4])

<li>when one operand is a scalar, numpy works as if it has created a second array
<li>ax + 5 is equivalent to ax + np.array([5,5,5,])
<li>note the "as if" because it doesn't actually do that
<li>instead it <b>broadcasts</b> the 5 to each element of ax
<li>we can do this broadcasting on any dimensional array

In [76]:
ay = np.ones([3,3])
ay

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
ax = np.array([1,2,3])
ax + ay

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

<b>broadcasting</b> won't work when arrays are of incompatible dimensions

In [78]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay

ValueError: operands could not be broadcast together with shapes (12,) (3,) 

<h4>np.newaxis is useful here because we can convert ax into a 2D array</h4>

In [79]:
ax[:,np.newaxis] + ay

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

In [80]:
#Broadcasting effectively does this:
ax[:,np.newaxis] + np.array([[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5]])

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

<h4>We could also convert ay into a 2D array</h4>
<li>the result will be different (why?) 

In [81]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay[:,np.newaxis]

array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]])

<h2>Fancy indexing</h2>
<li>numpy let's us work on indexed subsets of an nd array
<li>this lets us construct arbitrary subsets of an nd array in any dimension

In [82]:
ax = np.array([4,3,9,2,1,6])
ay = np.array([2,4])
ax[ay]

array([9, 1])

In [83]:
ay = np.array([[2,4],[1,3]])
ax[ay]

array([[9, 1],
       [3, 2]])

<h4>multi-dimentional indexes</h4>
<li>In a 2-d, index, the index array is used to generate (row_number,col_number) pairs

In [84]:
ax = np.array([[23,34,21,34,22],[33,44,11,29,32],[14,90,10,20,17]])
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] # [ax[0,1],ax[2,4]]

array([34, 17])

<h2>Universal functions</h2>
<li>functions that perform elementwise operations on arrays
<li>fast "wrapper" functions that produce scalar (or lower dimension) results
<li>sqrt, exp, add,maximum, minimum, abs, etc.
<li>https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [85]:
ax = np.array([1,2,3,4,5,6,7],float)
np.sqrt(ax)
np.exp(ax)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [86]:
ay = np.arange(10,17)
np.add(ax,ay)
np.maximum(ax,ay)

array([10., 11., 12., 13., 14., 15., 16.])

In [87]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [88]:
import scipy
scipy.nanmean(x)

12.5

<h3>Random number support in numpy</h3>

In [23]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([-0.89949532,  0.84919184,  0.81720139,  0.44382345, -0.30027543,
       -0.33172616, -0.27669278, -0.47884236,  1.04705612, -0.91109965])

In [24]:
np.random.normal(size=10, mean=0)

TypeError: normal() got an unexpected keyword argument 'mean'

In [26]:
y = np.random.normal(1000,1)
y

1000.5994716654374

In [28]:
ax = np.arange(18).reshape(6,3)

ax

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [31]:
ax[3:5,1:3]

array([[10, 11],
       [13, 14]])

In [39]:
ax = np.arange(18).reshape(6,3)
ax

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [56]:
ay = np.array([(0,2),(2,1)])
ax[ay]

array([[[0, 1, 2],
        [6, 7, 8]],

       [[6, 7, 8],
        [3, 4, 5]]])

In [63]:
ay = np.array([[0,2],[0,2]])
ax[ay]

array([[[0, 1, 2],
        [6, 7, 8]],

       [[0, 1, 2],
        [6, 7, 8]]])

In [65]:
ax[[2,0],[1,2]]
ay = np.array([[2,0],[1,2]])

array([[[6, 7, 8],
        [0, 1, 2]],

       [[3, 4, 5],
        [6, 7, 8]]])